### PR TITLE
Use macro for query initialization

### PR DESCRIPTION
**Pull request by ursachec**
Required for the traversalAsString value to be set automatically.

I've tried moving the queryInit().asInstanceOf[Query] to the method of a
separate object so that named parameters can be used and the casting at
the end is not needed, unfortunately the current macro takes the
argument's name as string instead of its expanded form. It might be
possible to create a new macro which doesn't do that and create a
prettier instantiation method, in the meantime this will have to do.

### CODE REVIEW

**Review by fabsx00 — APPROVED** [review]

**Comment by fabsx00** [comment]
@mpollmeier any ideas on how to resolve the remaining issues, that is, arguments aren't named anymore and we need to call the `queryInit` function + cast?

**Comment by mpollmeier** [comment]
Re named arguments I suppose we're out of luck, that's simply not supported. the error is quite clear about it: `macro applications do not support named and/or default arguments`

Could well be that that's changed in scala3.

**Comment by ursachec** [comment]
@mpollmeier if it's possible to follow an argument that represents the traversal back to its definition through one function, then we can simply have a function on a new object for the named parameters 

```
object QueryBuilder {
  def build(name: String, title: String, traversal: Cpg => Traversal[StoredNode]): Query = {
     queryInit(name, title, traversal).asInstanceOf[Query]
  }
}
```

**Comment by mpollmeier** [comment]
https://github.com/ShiftLeftSecurity/codepropertygraph/pull/1099 should fix the need for casting. @ursachec note the description - you probably want to move the Query class definition elsewhere

**Comment by mpollmeier** [comment]
>  if it's possible to follow an argument that represents the traversal back to its definition through one function, then we can simply have a function on a new object for the named parameters

@ursachec yes good idea, that should work. will push something like that to the same branch as above - same note will apply: you probably want to move it elsewhere

**Comment by mpollmeier** [comment]
actually, I take that back, with that indirection in place, the macro doesn't have access to the 'use-site' of the indirection. 
in other words, traversalAsString is always `traversal`, and not `cpg: Cpg => cpg.method`

So, the cast can be avoided, but I don't think we can get named parameters.

**Pull request merged**
